version: '3.8'

networks:
  kafka-playground-network:
    driver: bridge

services:
  redpanda:
    container_name: kafka-playground-redpanda-broker
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:29092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:29092
    ports:
      - 29092:29092
    networks:
      - kafka-playground-network

  redpanda-console:
    container_name: kafka-playground-redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    networks:
      - kafka-playground-network
    depends_on:
      - redpanda

  # client-auth-service:
  #   build: ./packages/client-auth-service
  #   volumes:
  #     - ./packages/client-auth-service:/app
  #   networks:
  #     - kafka-playground-network
  #   depends_on:
  #     - redpanda
